name: build-windows
on: push
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cache deps
      uses: actions/cache@v2
      env:
        cache-name: deps
      with:
          path: deps
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/build_win.bat') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - uses: GuillaumeFalourd/setup-windows10-sdk-action@v1
      with:
        sdk-version: 19041
    - name: build
      run: .\scripts\build_win.bat
