name: build
on: push
jobs:
  build_win:
    name: build on Windows
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Cache OBS-Studio deps
      uses: actions/cache@v2
      env:
        cache-name: obs
      with:
          path: deps/obs-studio
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/build_obs.bat') }}
    - name: build
      run: .\scripts\build_win.bat
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: windows-archive
        path: build/obs-virtualbg-*.zip
  build_mac:
    name: build on Mac
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: install deps
      run: brew install onnxruntime halide
    - name: install obs
      run: brew install --cask obs
    - name: build
      run: |
        mkdir build && \
        cd build && \
        cmake .. -DobLibPath=/Applications/OBS.app/Contents/Frameworks -DobsIncludePath=~/ghq/github.com/obsproject/obs-studio -DLLVM_DIR=/usr/local/Cellar/llvm/12.0.1/lib/cmake/llvm && \
        cmake --build . --config Release
    - name: pack
      run: cpack
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mac-archiveß
        path: build/obs-virtualbg-*.zip
