name: build-windows
on: push
jobs:
  build:
    name: build
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cache deps
      uses: actions/cache@v2
      env:
        cache-name: opencv
      with:
          path: deps/opencv
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/build_win.bat') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - name: Cache deps
      uses: actions/cache@v2
      env:
        cache-name: obs
      with:
          path: deps/obs-studio
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/build_win.bat') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - name: build
      run: .\scripts\build_win.bat
