on:
  release:
    types:
      - published

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Cache deps
      uses: actions/cache@v2
      env:
        cache-name: opencv
      with:
          path: deps/opencv
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/build_opencv.bat') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - name: Cache deps
      uses: actions/cache@v2
      env:
        cache-name: obs
      with:
          path: deps/obs-studio
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('scripts/build_obs.bat') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
    - name: build
      run: .\scripts\build_win.bat
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/obs-virtualbg-*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
